### total = type1 + type2 ######

totalParticles  : 63
type1_Particles : 63
type2_Particles : 0

particleRadius_1 : .1
particleRadius_2 : .12

seed            : 98638175623423
weight          : .2

numberUpdates  : 35000

hardDisks    : false
lennardJones : true
WCA          : false

crosslinkers   : false
restLength     : .22449
springConstant : 10
truncationDist : .4
beta           : .8

wellDepth : 2         # corresponds unit of energy
sigma : .2

rigidBoundary    : false 
periodicBoundary : true 
externalWell     : false

boxLength   : 1

