### total = type1 + type2 ######

totalParticles  : 5
type1_Particles : 2
type2_Particles : 3

seed            : 62384925602983
weight          : .3

particleRadius_1 : .1
particleRadius_2 : .12

numberUpdates  : 300

hardDisks    : true
lennardJones : false
WCA          : false 

wellDepth : 4

rigidBoundary    : false 
periodicBoundary : false  
externalWell     : true

# convergence_test    : false

boxLength   : 1 
