### total = type1 + type2 ######

totalParticles  : 5
type1_Particles : 2
type2_Particles : 3

seed            : 62384925602983
weight          : .3

particleRadius_1 : .1
particleRadius_2 : .085

numberUpdates  : 50

hardDisks    : false
lennardJones : false
WCA          : true 

wellDepth : 4

rigidBoundary       : true 
periodicBoundary    : false  

# convergence_test    : false

boxLength   : 1 
