### total = type1 + type2 ######

totalParticles  : 500 
type1_Particles : 500
type2_Particles : 0

particleRadius_1 : .03
particleRadius_2 : .12

seed            : 98638175623423
weight          : .06

numberUpdates  : 2000

initializationType : 1 # 0 = random, 1 = hexagonal
                       # 2 = square
hardDisks    : false
lennardJones : true
WCA          : false

crosslinkers   : false
restLength     : .22449
springConstant : 10
truncationDist : .4
beta           : .5

wellDepth : 1         # corresponds unit of energy
sigma : .1            # RD = 1

rigidBoundary    : false 
periodicBoundary : true 
externalWell     : false

boxLength   : 1.33630621

animationFile : positions.txt
