### total = type1 + type2 ######

totalParticles  : 7
type1_Particles : 3
type2_Particles : 4

seed            : 756534526765
weight          : .3

particleRadius_1 : .15
particleRadius_2 : .1

numberUpdates  : 1000

hardDisks    : false
lennardJones : false
WAC          : true 

wellDepth : 50

# internalPotential   : false
# externalPotential   : false
rigidBoundary       : true 
periodicBoundary    : false  

# convergence_test    : false

boxLength   : 1 
# restLength  : 1