### total = type1 + type2 ######

totalParticles  : 50
type1_Particles : 50
type2_Particles : 0

seed            : 98638175623423
weight          : .15

particleRadius_1 : .12
particleRadius_2 : .12

numberUpdates  : 10000

hardDisks    : false
lennardJones : false
WCA          : true

crosslinkers   : false 
restLength     : .24
springConstant : 20
truncationDist : .28

wellDepth : 1

rigidBoundary    : false 
periodicBoundary : true 
externalWell     : false

boxLength   : 1.2

