### total = type1 + type2 ######

totalParticles  : 40
type1_Particles : 25
type2_Particles : 15
 # - Total : 2
 # - One   : 1
 # - Two   : 1

seed            : 8625938934095
weight          : .3

particleRadius_1 : .05
particleRadius_2 : .1

numberUpdates  : 1000

hardDisks : true

# internalPotential   : false
# externalPotential   : false
rigidBoundary       : true 
# periodicBoundary    : false  

# convergence_test    : false

boxLength   : 1 
# restLength  : 1