### total = type1 + type2 ######

totalParticles  : 7
type1_Particles : 3
type2_Particles : 4

seed            : 756534526765
weight          : .3

particleRadius_1 : .15
particleRadius_2 : .1

numberUpdates  : 100

hardDisks    : false
lennardJones : true

wellDepth : .7

# internalPotential   : false
# externalPotential   : false
rigidBoundary       : false 
periodicBoundary    : true  

# convergence_test    : false

boxLength   : 1 
# restLength  : 1