### total = type1 + type2 ######

totalParticles  : 27
type1_Particles : 18
type2_Particles : 9

seed            : 756534526765
weight          : .2

particleRadius_1 : .08
particleRadius_2 : .1

numberUpdates  : 1000

hardDisks    : false
lennardJones : true

wellDepth : .7

# internalPotential   : false
# externalPotential   : false
rigidBoundary       : true 
# periodicBoundary    : false  

# convergence_test    : false

boxLength   : 1 
# restLength  : 1