### total = type1 + type2 ######

totalParticles  : 50
type1_Particles : 15
type2_Particles : 35

seed            : 62384925602983
weight          : .3

particleRadius_1 : .15
particleRadius_2 : .12

numberUpdates  : 300

hardDisks    : true
lennardJones : false
WCA          : false 

wellDepth : 4

rigidBoundary    : true 
periodicBoundary : false  
externalWell     : false

boxLength   : 1.3
