### total = type1 + type2 ######

totalParticles  : 256 
type1_Particles : 256
type2_Particles : 0

particleRadius_1 : .05
particleRadius_2 : .12

## DEFINE THE REDUCED PARAMS ###

reducedTemp : .7  # not measured by the system currently
reducedDens : .9  # currently user determined, but could be found from sigma,L
sigma       : 1    # if = 0, then sigma = Lsqrt(p^*/NumPart)
boxLength   : 0    # if = 0, then L = sigma sqrt(N/p^*)

seed   : 20394750231 
weight : .06 # weight is being calculated inside the program

numberUpdates  : 1500  # each update = 1 sweep = n_part attempted moves 
initializationType : 1 # 0 = random, 1 = hexagonal, 2 = square

### CHOOSE INTERACTION TYPE ####

hardDisks    : false
lennardJones : true
WCA          : false

# wellDepth : 1    this unit of energy shouldn't be necessary if 
                 # everything is nondimensionalized properly

### DEFINE TYPE OF BOUNDARY ######

rigidBoundary    : false 
periodicBoundary : true # primarily working with periodic boundaries for now
externalWell     : false # so the other BC will need a fair amount of work 

animationFile : positions.txt
