### total = type1 + type2 ######

totalParticles  : 40
type1_Particles : 40
type2_Particles : 0

seed            : 98638175623423
weight          : .3

particleRadius_1 : .13
particleRadius_2 : .12

numberUpdates  : 300

hardDisks    : true
lennardJones : false
WCA          : false 

crosslinkers   : true 
restLength     : .3676955
springConstant : 15
truncationDist : .5

wellDepth : 4

rigidBoundary    : false 
periodicBoundary : false  
externalWell     : true

boxLength   : 1.1

