### total = type1 + type2 ######

totalParticles  : 16
type1_Particles : 8
type2_Particles : 8

seed            : 62384925602983
weight          : .3

particleRadius_1 : .1
particleRadius_2 : .085

numberUpdates  : 50

hardDisks    : false
lennardJones : true
WAC          : false 

wellDepth : 4

# internalPotential   : false
# externalPotential   : false
rigidBoundary       : false 
periodicBoundary    : true  

# convergence_test    : false

boxLength   : 1 
# restLength  : 1