### total = type1 + type2 ######

totalParticles  : 256 
type1_Particles : 256 
type2_Particles : 0

particleRadius: .05

# DEFINE THE REDUCED PARAMS ###

reducedTemp : 1  # not measured by the system currently
reducedDens : .7  # currently user determined, but could be found from sigma,L
sigma       : 1    # if = 0, then sigma = Lsqrt(p^*/NumPart)
boxLength   : 0    # if = 0, then L = sigma sqrt(N/p^*)

LJ_constant_1 : 1  # thus the well depth for each is equal to 
LJ_constant_2 : 1.5  # c * KbT

seed   : 90757029382  
weight : .06 # weight is being calculated inside the program

numberUpdates  : 30000  # each update = 1 sweep = n_part attempted moves 
initializationType : 1 # 0 = random, 1 = hexagonal, 2 = square

### CHOOSE RUN LENGTH ####

equilibriate_sweep : 15000 
data_collect_interval : 50

### CHOOSE INTERACTION TYPE ####

interactionType : 1 # 0 = hard disk, 1 = LJ, 2 = WCA

### DEFINE TYPE OF BOUNDARY ######

boundaryType : 1 # 0 = rigid, 1 = periodic, 2 = external well 
rigidBoundary    : false # change these form bool values... should be handled 
                         # more similarly to the initialization. 
periodicBoundary : true # primarily working with periodic boundaries for now
externalWell     : false # so the other BC will need a fair amount of work 

animationFile : positions.txt
